"use strict";
let places = ["china", "switzerland", "jordan", "malaisha"];
console.log("original order:", places);
console.log("alphabetical order:", [...places].sort());
console.log("origional order:", places);
console.log("reversed order:", places);
places.reverse();
console.log("original order:", places);
places.sort();
console.log("alphabetical order:", places);
places.reverse();
console.log("reverse alphabetical order:", places);
